"""editable e hidden status su character

Revision ID: 87a604933b41
Revises: b08f4c18d955
Create Date: 2024-03-08 10:01:52.288850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a604933b41'
down_revision = 'b08f4c18d955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('editable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('hidden')
        batch_op.drop_column('editable')

    # ### end Alembic commands ###
