"""aggiunto plane a character

Revision ID: b08f4c18d955
Revises: 6a2d8617768e
Create Date: 2024-01-14 13:48:30.872739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b08f4c18d955'
down_revision = '6a2d8617768e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plane', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_character_plane'), ['plane'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_plane'))
        batch_op.drop_column('plane')

    # ### end Alembic commands ###
